---
- name: Lancement du playbook en local
  hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: no

  tasks:
   - name: add key vscode
     apt_key:
             url: https://packages.microsoft.com/keys/microsoft.asc
             state: present
             keyring: /usr/share/keyrings/packages.microsoft.gpg

   - name: add repo vscode          
     apt_repository:
                    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main
                    state: present

   - name: update cache apt
     apt:
         update_cache: yes

   - name: update system
     apt:
         upgrade: yes

   - name: installations basic tools
     apt:
         name: "{{ packages }}"
         state: present
     vars:
       packages:
         - htop
         - git
         - traceroute
         - python3-pip
         - openvpn
         - ubuntu-unity-desktop
         - aptitude
         - terminator
         - locate
         - curl
         - apt-transport-https

   - name: install vscode
     apt:
         name: code
         state: present
